
package service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DepartamentoService", targetNamespace = "http://Service/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DepartamentoService {


    /**
     * 
     */
    @WebMethod(operationName = "DepartamentosService")
    @Action(input = "http://Service/DepartamentoService/DepartamentosServiceRequest", output = "http://Service/DepartamentoService/DepartamentosServiceResponse")
    public void departamentosService();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     */
    @WebMethod
    @Action(input = "http://Service/DepartamentoService/altaDepartamentoServiceRequest", output = "http://Service/DepartamentoService/altaDepartamentoServiceResponse")
    public void altaDepartamentoService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @return
     *     returns service.ListaString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getSetDepartamentosServiceRequest", output = "http://Service/DepartamentoService/getSetDepartamentosServiceResponse")
    public ListaString getSetDepartamentosService();

    /**
     * 
     * @return
     *     returns service.ListaString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getCategoriasServiceRequest", output = "http://Service/DepartamentoService/getCategoriasServiceResponse")
    public ListaString getCategoriasService();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Service/DepartamentoService/altaCategoriaServiceRequest", output = "http://Service/DepartamentoService/altaCategoriaServiceResponse")
    public void altaCategoriaService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getDepartamentoXActividadServiceRequest", output = "http://Service/DepartamentoService/getDepartamentoXActividadServiceResponse")
    public String getDepartamentoXActividadService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/existeSalidaServiceRequest", output = "http://Service/DepartamentoService/existeSalidaServiceResponse")
    public boolean existeSalidaService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns service.DataMapSalida
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getSalidasXFechaServiceRequest", output = "http://Service/DepartamentoService/getSalidasXFechaServiceResponse")
    public DataMapSalida getSalidasXFechaService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @return
     *     returns service.DataMapActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getActividadesAgregadasServiceRequest", output = "http://Service/DepartamentoService/getActividadesAgregadasServiceResponse")
    public DataMapActividad getActividadesAgregadasService();

    /**
     * 
     * @param arg0
     * @return
     *     returns service.DtSalida
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getSalidaNombreServiceRequest", output = "http://Service/DepartamentoService/getSalidaNombreServiceResponse")
    public DtSalida getSalidaNombreService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/existeCategoriaServiceRequest", output = "http://Service/DepartamentoService/existeCategoriaServiceResponse")
    public boolean existeCategoriaService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Service/DepartamentoService/finalizarActividadServiceRequest", output = "http://Service/DepartamentoService/finalizarActividadServiceResponse")
    public void finalizarActividadService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     */
    @WebMethod
    @Action(input = "http://Service/DepartamentoService/altaActividadServiceRequest", output = "http://Service/DepartamentoService/altaActividadServiceResponse")
    public void altaActividadService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4,
        @WebParam(name = "arg5", partName = "arg5")
        int arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.DataMapActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getActividadesXCatServiceRequest", output = "http://Service/DepartamentoService/getActividadesXCatServiceResponse")
    public DataMapActividad getActividadesXCatService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns service.DataMapCategoria
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getMapCategoriasServiceRequest", output = "http://Service/DepartamentoService/getMapCategoriasServiceResponse")
    public DataMapCategoria getMapCategoriasService();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getActividadXSalidaServiceRequest", output = "http://Service/DepartamentoService/getActividadXSalidaServiceResponse")
    public String getActividadXSalidaService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/existeDepartamentoServiceRequest", output = "http://Service/DepartamentoService/existeDepartamentoServiceResponse")
    public boolean existeDepartamentoService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns service.DtSalida
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getSalidaXActividadServiceRequest", output = "http://Service/DepartamentoService/getSalidaXActividadServiceResponse")
    public DtSalida getSalidaXActividadService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @return
     *     returns service.DataMapActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getActividadesAceptadasServiceRequest", output = "http://Service/DepartamentoService/getActividadesAceptadasServiceResponse")
    public DataMapActividad getActividadesAceptadasService();

    /**
     * 
     * @param arg0
     * @return
     *     returns service.DataMapActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getActividadesXDepServiceRequest", output = "http://Service/DepartamentoService/getActividadesXDepServiceResponse")
    public DataMapActividad getActividadesXDepService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns service.DataMapSalida
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getSalidaXActividadDeptoServiceRequest", output = "http://Service/DepartamentoService/getSalidaXActividadDeptoServiceResponse")
    public DataMapSalida getSalidaXActividadDeptoService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.DataActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/encontrarActividadServiceRequest", output = "http://Service/DepartamentoService/encontrarActividadServiceResponse")
    public DataActividad encontrarActividadService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://Service/DepartamentoService/aceptarActividadServiceRequest", output = "http://Service/DepartamentoService/aceptarActividadServiceResponse")
    public void aceptarActividadService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.DataMapActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getActividadesAgregadasXDepServiceRequest", output = "http://Service/DepartamentoService/getActividadesAgregadasXDepServiceResponse")
    public DataMapActividad getActividadesAgregadasXDepService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns service.DataMapActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getActividadesAceptadasSinSalidaServiceRequest", output = "http://Service/DepartamentoService/getActividadesAceptadasSinSalidaServiceResponse")
    public DataMapActividad getActividadesAceptadasSinSalidaService();

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/existeActividadEnDepartamentoServiceRequest", output = "http://Service/DepartamentoService/existeActividadEnDepartamentoServiceResponse")
    public boolean existeActividadEnDepartamentoService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://Service/DepartamentoService/agregarActividadACategoriaStringServiceRequest", output = "http://Service/DepartamentoService/agregarActividadACategoriaStringServiceResponse")
    public void agregarActividadACategoriaStringService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns service.DataMapSalida
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/DepartamentoService/getsalidasServiceRequest", output = "http://Service/DepartamentoService/getsalidasServiceResponse")
    public DataMapSalida getsalidasService();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     */
    @WebMethod
    @Action(input = "http://Service/DepartamentoService/crearSalidaServiceRequest", output = "http://Service/DepartamentoService/crearSalidaServiceResponse")
    public void crearSalidaService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        int arg6);

}
