
package service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UsuarioService", targetNamespace = "http://Service/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuarioService {


    /**
     * 
     * @return
     *     returns service.ListaString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/getSetProveedorServiceRequest", output = "http://Service/UsuarioService/getSetProveedorServiceResponse")
    public ListaString getSetProveedorService();

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/existeInscripServiceRequest", output = "http://Service/UsuarioService/existeInscripServiceResponse")
    public boolean existeInscripService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns service.ListaString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/getProveedoresServiceRequest", output = "http://Service/UsuarioService/getProveedoresServiceResponse")
    public ListaString getProveedoresService();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     */
    @WebMethod
    @Action(input = "http://Service/UsuarioService/altaProveedorServiceRequest", output = "http://Service/UsuarioService/altaProveedorServiceResponse")
    public void altaProveedorService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/existeNicknameServiceRequest", output = "http://Service/UsuarioService/existeNicknameServiceResponse")
    public boolean existeNicknameService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     */
    @WebMethod
    @Action(input = "http://Service/UsuarioService/registrarInscripServiceRequest", output = "http://Service/UsuarioService/registrarInscripServiceResponse")
    public void registrarInscripService(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.DataMapSalida
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/getSalidasUsuServiceRequest", output = "http://Service/UsuarioService/getSalidasUsuServiceResponse")
    public DataMapSalida getSalidasUsuService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/verificarContraseniaRequest", output = "http://Service/UsuarioService/verificarContraseniaResponse")
    public boolean verificarContrasenia(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.DataMapActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/getAvtividadesUsuServiceRequest", output = "http://Service/UsuarioService/getAvtividadesUsuServiceResponse")
    public DataMapActividad getAvtividadesUsuService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.DtUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/getUsuarioNickServiceRequest", output = "http://Service/UsuarioService/getUsuarioNickServiceResponse")
    public DtUsuario getUsuarioNickService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.DataMapActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/getActividadesAceptadasServiceRequest", output = "http://Service/UsuarioService/getActividadesAceptadasServiceResponse")
    public DataMapActividad getActividadesAceptadasService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns service.ListaString
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/getTuristasServiceRequest", output = "http://Service/UsuarioService/getTuristasServiceResponse")
    public ListaString getTuristasService();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     */
    @WebMethod
    @Action(input = "http://Service/UsuarioService/altaTuristaServiceRequest", output = "http://Service/UsuarioService/altaTuristaServiceResponse")
    public void altaTuristaService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6);

    /**
     * 
     */
    @WebMethod(operationName = "UsuarioService")
    @Action(input = "http://Service/UsuarioService/UsuarioServiceRequest", output = "http://Service/UsuarioService/UsuarioServiceResponse")
    public void usuarioService();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/existeMailServiceRequest", output = "http://Service/UsuarioService/existeMailServiceResponse")
    public boolean existeMailService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns service.DataMapUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/getUsuarioServiceRequest", output = "http://Service/UsuarioService/getUsuarioServiceResponse")
    public DataMapUsuario getUsuarioService();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/esTuristaRequest", output = "http://Service/UsuarioService/esTuristaResponse")
    public boolean esTurista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.DtTurista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/getTuristaRequest", output = "http://Service/UsuarioService/getTuristaResponse")
    public DtTurista getTurista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.DtProveedor
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Service/UsuarioService/getProveedorRequest", output = "http://Service/UsuarioService/getProveedorResponse")
    public DtProveedor getProveedor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
