
package service;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UsuarioServiceService", targetNamespace = "http://Service/", wsdlLocation = "http://localhost:7970/UsuarioService?wsdl")
public class UsuarioServiceService
    extends Service
{

    private final static URL USUARIOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException USUARIOSERVICESERVICE_EXCEPTION;
    private final static QName USUARIOSERVICESERVICE_QNAME = new QName("http://Service/", "UsuarioServiceService");

    static {
        URL url = null;
        String puerto = "7960";
        WebServiceException e = null;
			InputStream input;
			try {
				
				input = new FileInputStream(System.getProperty("user.home")+File.separator+".turismoUy"+File.separator+"config.properties");
				Properties propiedades = new Properties();
				propiedades.load(input);
				puerto = (String) propiedades.get("puertoUsuM");
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			// TODO Auto-generated catch block
	
        try {
            url = new URL("http://localhost:"+puerto+"/UsuarioService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USUARIOSERVICESERVICE_WSDL_LOCATION = url;
        USUARIOSERVICESERVICE_EXCEPTION = e;
    }

    public UsuarioServiceService() {
        super(__getWsdlLocation(), USUARIOSERVICESERVICE_QNAME);
    }

    public UsuarioServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIOSERVICESERVICE_QNAME, features);
    }

    public UsuarioServiceService(URL wsdlLocation) {
        super(wsdlLocation, USUARIOSERVICESERVICE_QNAME);
    }

    public UsuarioServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIOSERVICESERVICE_QNAME, features);
    }

    public UsuarioServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsuarioService
     */
    @WebEndpoint(name = "UsuarioServicePort")
    public UsuarioService getUsuarioServicePort() {
        return super.getPort(new QName("http://Service/", "UsuarioServicePort"), UsuarioService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioService
     */
    @WebEndpoint(name = "UsuarioServicePort")
    public UsuarioService getUsuarioServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service/", "UsuarioServicePort"), UsuarioService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIOSERVICESERVICE_EXCEPTION!= null) {
            throw USUARIOSERVICESERVICE_EXCEPTION;
        }
        return USUARIOSERVICESERVICE_WSDL_LOCATION;
    }

}
